#!/bin/bash
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --tasks-per-node=2
#SBATCH --job-name=sharringan
##SBATCH --time=06:00:00
#SBATCH --mail-user=rgudipat@buffalo.edu
#SBATCH --output=MR-MPI.out
#SBATCH --error=MR-MPI.out

echo "SLURM Environment Variables:"
echo "Job ID = "$SLURM_JOB_ID
echo "Job Name = "$SLURM_JOB_NAME
echo "Job Node List = "$SLURM_JOB_NODELIST
echo "Number of Nodes = "$SLURM_NNODES
echo "Tasks per node = "$SLURM_NTASKS_PER_NODE
echo "CPUs per task = "$SLURM_CPUS_PER_TASK
echo "/scratch/jobid = "$SLURMTMPDIR
echo "Submit Host = "$SLURM_SUBMIT_HOST
echo "Submit Directory = "$SLURM_SUBMIT_DIR
echo 
echo

ulimit -s unlimited
#
mpirun -n 2 wordfreq tst.txt
echo "All Done!"
